// frameworks/solid/add-ons/better-auth/assets/src/integrations/better-auth/header-user.tsx
import { Show } from "solid-js";
import { Link } from "@tanstack/solid-router";
import { authClient } from "../../lib/auth-client";

export default function BetterAuthHeader() {
  const session = authClient.useSession();

  return (
    <Show
      when={!session().isPending}
      fallback={
        <div class="h-8 w-8 bg-neutral-100 dark:bg-neutral-800 animate-pulse" />
      }
    >
      <Show
        when={session().data?.user}
        fallback={
          <Link
            to="/demo/better-auth"
            class="h-9 px-4 text-sm font-medium bg-white dark:bg-neutral-900 text-neutral-900 dark:text-neutral-50 border border-neutral-300 dark:border-neutral-700 hover:bg-neutral-50 dark:hover:bg-neutral-800 transition-colors inline-flex items-center"
          >
            Sign in
          </Link>
        }
      >
        {(user) => (
          <div class="flex items-center gap-2">
            <Show
              when={user().image}
              fallback={
                <div class="h-8 w-8 bg-neutral-100 dark:bg-neutral-800 flex items-center justify-center">
                  <span class="text-xs font-medium text-neutral-600 dark:text-neutral-400">
                    {user().name?.charAt(0).toUpperCase() || "U"}
                  </span>
                </div>
              }
            >
              {(image) => <img src={image()} alt="" class="h-8 w-8" />}
            </Show>
            <button
              onClick={() => authClient.signOut()}
              class="flex-1 h-9 px-4 text-sm font-medium bg-white dark:bg-neutral-900 text-neutral-900 dark:text-neutral-50 border border-neutral-300 dark:border-neutral-700 hover:bg-neutral-50 dark:hover:bg-neutral-800 transition-colors"
            >
              Sign out
            </button>
          </div>
        )}
      </Show>
    </Show>
  );
}

// packages/cta-engine/templates/react/add-on/better-auth/assets/src/integrations/better-auth/header-user.tsx
import { authClient } from "@/lib/auth-client";

export default function HeaderUser() {
	return (
		<div className="flex items-center justify-center gap-2">
			<Avatar />
			<LogoutButton />
		</div>
	);
}

function Avatar() {
	const { data } = authClient.useSession();
	const user = data?.user;
	if (!user) return null;
	return (
		<div className="relative inline-flex items-center justify-center w-6 h-6 overflow-hidden bg-gray-100 rounded-full dark:bg-gray-600">
			<span className="text-xs font-medium text-gray-600 dark:text-gray-300 uppercase">
				{user.name.slice(0, 2)}
			</span>
		</div>
	);
}

function LogoutButton() {
	const { data } = authClient.useSession();
	const session = data?.session;
	if (!session) return null;
	return (
		<button
			onClick={() => authClient.signOut()}
			type="button"
			className="focus:outline-none text-white bg-red-700 hover:bg-red-800 focus:ring-4 focus:ring-red-300 font-medium rounded-lg text-xs px-2 py-1 dark:bg-red-600 dark:hover:bg-red-700 dark:focus:ring-red-900"
		>
			Logout
		</button>
	);
}
