// frameworks/solid/add-ons/better-auth/assets/src/integrations/better-auth/header-user.tsx
import { Show } from "solid-js";
import { Link } from "@tanstack/solid-router";
import { authClient } from "../../lib/auth-client";

export default function BetterAuthHeader() {
  const session = authClient.useSession();

  return (
    <Show
      when={!session().isPending}
      fallback={
        <div class="h-8 w-8 bg-neutral-100 dark:bg-neutral-800 animate-pulse" />
      }
    >
      <Show
        when={session().data?.user}
        fallback={
          <Link
            to="/demo/better-auth"
            class="h-9 px-4 text-sm font-medium bg-white dark:bg-neutral-900 text-neutral-900 dark:text-neutral-50 border border-neutral-300 dark:border-neutral-700 hover:bg-neutral-50 dark:hover:bg-neutral-800 transition-colors inline-flex items-center"
          >
            Sign in
          </Link>
        }
      >
        {(user) => (
          <div class="flex items-center gap-2">
            <Show
              when={user().image}
              fallback={
                <div class="h-8 w-8 bg-neutral-100 dark:bg-neutral-800 flex items-center justify-center">
                  <span class="text-xs font-medium text-neutral-600 dark:text-neutral-400">
                    {user().name?.charAt(0).toUpperCase() || "U"}
                  </span>
                </div>
              }
            >
              {(image) => <img src={image()} alt="" class="h-8 w-8" />}
            </Show>
            <button
              onClick={() => authClient.signOut()}
              class="flex-1 h-9 px-4 text-sm font-medium bg-white dark:bg-neutral-900 text-neutral-900 dark:text-neutral-50 border border-neutral-300 dark:border-neutral-700 hover:bg-neutral-50 dark:hover:bg-neutral-800 transition-colors"
            >
              Sign out
            </button>
          </div>
        )}
      </Show>
    </Show>
  );
}

// packages/create/src/frameworks/react/add-ons/better-auth/assets/src/integrations/better-auth/header-user.tsx
import { authClient } from "@/lib/auth-client";
import { Link } from "@tanstack/react-router";

export default function BetterAuthHeader() {
  const { data: session, isPending } = authClient.useSession();

  if (isPending) {
    return (
      <div className="h-8 w-8 bg-neutral-100 dark:bg-neutral-800 animate-pulse" />
    );
  }

  if (session?.user) {
    return (
      <div className="flex items-center gap-2">
        {session.user.image ? (
          <img src={session.user.image} alt="" className="h-8 w-8" />
        ) : (
          <div className="h-8 w-8 bg-neutral-100 dark:bg-neutral-800 flex items-center justify-center">
            <span className="text-xs font-medium text-neutral-600 dark:text-neutral-400">
              {session.user.name?.charAt(0).toUpperCase() || "U"}
            </span>
          </div>
        )}
        <button
          onClick={() => {
            void authClient.signOut()
          }}
          className="flex-1 h-9 px-4 text-sm font-medium bg-white dark:bg-neutral-900 text-neutral-900 dark:text-neutral-50 border border-neutral-300 dark:border-neutral-700 hover:bg-neutral-50 dark:hover:bg-neutral-800 transition-colors"
        >
          Sign out
        </button>
      </div>
    );
  }

  return (
    <Link
      to="/demo/better-auth"
      className="h-9 px-4 text-sm font-medium bg-white dark:bg-neutral-900 text-neutral-900 dark:text-neutral-50 border border-neutral-300 dark:border-neutral-700 hover:bg-neutral-50 dark:hover:bg-neutral-800 transition-colors inline-flex items-center"
    >
      Sign in
    </Link>
  );
}
